services:
    db:
        image: postgres:15-alpine
        environment:
            POSTGRES_DB: ${POSTGRES_DB:-cruso}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
            POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256 --auth-local=scram-sha-256"
        ports:
            - '5432:5432'
        volumes:
            - postgres_data:/var/lib/postgresql/data
        healthcheck:
            test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
            interval: 10s
            timeout: 5s
            retries: 5

    app:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '3000:3000'
        env_file:
            - .env.local
        environment:
            - NODE_ENV=development
            - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-cruso}
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        depends_on:
            db:
                condition: service_healthy
        command: pnpm dev

volumes:
    postgres_data:
