import { pgTable, serial, varchar, boolean, index } from 'drizzle-orm/pg-core';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';

/**
 * Allowed List Table - Email spam filtering allowlist/blocklist
 */
export const allowedList = pgTable(
    'allowed_list',
    {
        id: serial('id').primaryKey(),
        email: varchar('email', { length: 255 }).notNull(),
        isAllowed: boolean('is_allowed').notNull().default(true),
    },
    (table) => [
        index('idx_allowed_list_email').on(table.email),
        index('idx_allowed_list_is_allowed').on(table.isAllowed),
    ],
);

/**
 * Autogenerated zod schema
 */
export const insertAllowedListSchema = createInsertSchema(allowedList);
export const selectAllowedListSchema = createSelectSchema(allowedList);
