import {
    pgTable,
    serial,
    timestamp,
    varchar,
    integer,
    index,
    date,
    time,
    text,
    boolean,
} from 'drizzle-orm/pg-core';
import { relations } from 'drizzle-orm';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';
import { calendarConnections } from './calendars';
import { preferences } from './preferences';
import { userEmails } from './user-emails';
import { availability } from './availability';

// Users Table - Primary table for handling user data
export const users = pgTable('users', {
    id: serial('id').primaryKey(),
    email: varchar('email', { length: 255 }).notNull().unique(),
    createdAt: timestamp('created_at').defaultNow(),
    updatedAt: timestamp('updated_at').defaultNow(),
});

// Relations - Only used for ORM
export const usersRelations = relations(users, ({ many }) => ({
    emails: many(userEmails),
    availability: many(availability),
    preferences: many(preferences),
    calendarConnections: many(calendarConnections),
}));

// Autogenerated zod schema
export const insertUserSchema = createInsertSchema(users);
export const selectUserSchema = createSelectSchema(users);
