import {
    pgTable,
    serial,
    integer,
    varchar,
    time,
    timestamp,
    index,
    text,
} from 'drizzle-orm/pg-core';
import { user } from '@/db/schema/auth';
import { relations } from 'drizzle-orm';
import { createInsertSchema, createSelectSchema } from 'drizzle-zod';

/**
 * Working Hours Table - Flexible working hours system (like Cal.com)
 */
export const workingHours = pgTable(
    'working_hours',
    {
        id: serial('id').primaryKey(),
        userId: text('user_id').references(() => user.id, {
            onDelete: 'cascade',
        }),
        days: integer('days').array(), // [1,2,3,4,5] for Mon-Fri
        startTime: time('start_time').notNull(),
        endTime: time('end_time').notNull(),
        timezone: varchar('timezone', { length: 100 }).notNull(),
        createdAt: timestamp('created_at').defaultNow(),
        updatedAt: timestamp('updated_at').defaultNow(),
    },
    (table) => [index('idx_working_hours_user_days').on(table.userId, table.days)],
);

/**
 * Relations - Only used for ORM
 */
export const workingHoursRelations = relations(workingHours, ({ one }) => ({
    user: one(user, {
        fields: [workingHours.userId],
        references: [user.id],
    }),
}));

/**
 * Autogenerated zod schema
 */
export const insertWorkingHoursSchema = createInsertSchema(workingHours, {
    startTime: (schema) => schema.regex(/^\d{2}:\d{2}(:\d{2})?$/, 'Invalid time format'),
    endTime: (schema) => schema.regex(/^\d{2}:\d{2}(:\d{2})?$/, 'Invalid time format'),
    days: (schema) => schema.optional(),
});
export const selectWorkingHoursSchema = createSelectSchema(workingHours);
